sudo: required
dist: trusty
language: node_js

env:
  matrix:
    - NODE_VERSION="4" NPM_VERSION="3" DISPLAY=:99
    - NODE_VERSION="5" NPM_VERSION="3" DISPLAY=:99
    - NODE_VERSION="5" NPM_VERSION="3" DISPLAY=:99
    - NODE_VERSION="6" NPM_VERSION="3" DISPLAY=:99
    - NODE_VERSION="6" NPM_VERSION="4" DISPLAY=:99
    - NODE_VERSION="7" NPM_VERSION="3" DISPLAY=:99
    - NODE_VERSION="7" NPM_VERSION="4" DISPLAY=:99
    - NODE_VERSION="8" NPM_VERSION="5" DISPLAY=:99
    - NODE_VERSION="9" NPM_VERSION="5" DISPLAY=:99

cache:
  directories:
    - "node_modules"


before_install:
  # Prepare node and npm
  - nvm install $NODE_VERSION && nvm use $NODE_VERSION
  - npm install -g npm@$NPM_VERSION
  - jdk_switcher use oraclejdk8
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 +extension RANDR -ac -screen 0 1280x1024x16"
before_script:
  - npm install -g grunt
  - npm install -g jshint
  - npm install -g mocha
  - npm install -g istanbul
  - npm install -g istanbul-coveralls
  - npm install -g nodeunit
  - npm install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - npm test