sudo: required
dist: trusty
language: node_js
node_js:
  - "4.0"
  - "4.3"
  - "4"
  - "5.0"
  - "5"
  - "6"
  - "7"
  - "stable"
env:
  - NPM_VERSION=4
  - NPM_VERSION=3
before_install:
  - jdk_switcher use oraclejdk8
  - npm install -g npm@$NPM_VERSION
before_script:
  - npm install -g gulp
  - npm install -g jshint
  - npm install -g mocha
  - npm install -g istanbul
  - npm install -g istanbul-coveralls
  - npm install -g nodeunit
  - npm install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - npm test